# Dependabot configuration for dynamic-pricing-strategies-ml
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
    # Set review requirements and limits
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    # Group minor and patch updates
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
